// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpinService_Spin_FullMethodName = "/spin.SpinService/Spin"
)

// SpinServiceClient is the client API for SpinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpinServiceClient interface {
	Spin(ctx context.Context, in *SpinRequest, opts ...grpc.CallOption) (*SpinResponse, error)
}

type spinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpinServiceClient(cc grpc.ClientConnInterface) SpinServiceClient {
	return &spinServiceClient{cc}
}

func (c *spinServiceClient) Spin(ctx context.Context, in *SpinRequest, opts ...grpc.CallOption) (*SpinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpinResponse)
	err := c.cc.Invoke(ctx, SpinService_Spin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpinServiceServer is the server API for SpinService service.
// All implementations must embed UnimplementedSpinServiceServer
// for forward compatibility.
type SpinServiceServer interface {
	Spin(context.Context, *SpinRequest) (*SpinResponse, error)
	mustEmbedUnimplementedSpinServiceServer()
}

// UnimplementedSpinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpinServiceServer struct{}

func (UnimplementedSpinServiceServer) Spin(context.Context, *SpinRequest) (*SpinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Spin not implemented")
}
func (UnimplementedSpinServiceServer) mustEmbedUnimplementedSpinServiceServer() {}
func (UnimplementedSpinServiceServer) testEmbeddedByValue()                     {}

// UnsafeSpinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpinServiceServer will
// result in compilation errors.
type UnsafeSpinServiceServer interface {
	mustEmbedUnimplementedSpinServiceServer()
}

func RegisterSpinServiceServer(s grpc.ServiceRegistrar, srv SpinServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpinService_ServiceDesc, srv)
}

func _SpinService_Spin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpinServiceServer).Spin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpinService_Spin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpinServiceServer).Spin(ctx, req.(*SpinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpinService_ServiceDesc is the grpc.ServiceDesc for SpinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spin.SpinService",
	HandlerType: (*SpinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spin",
			Handler:    _SpinService_Spin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
