FROM golang:1.21.9-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main server.go

FROM alpine:latest  

WORKDIR /root/

COPY --from=builder /app/main .

CMD ["./main"]

