apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grpc-server
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: junkemao/grpc-server:v1
          ports:
            - name: h2c
              containerPort: 50051
